FROM registry.dev.proneer.co/core-gpu:latest

### tzdata Dependencies
ARG DEBIAN_FRONTEND=noninteractive
ENV TZ="Etc/UTC"
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

### Install extra packages
RUN apt-get update && apt-get install -y \
    htop \
    screen \
    tmux \
    emacs \
    vim \
	zip \
	unzip \
    make \
    cmake \
    build-essential \
    netcat \
    locales \
    tzdata \
    ca-certificates \
    jq \
    less \
    # Fix permissions
    && fix-permissions.sh $HOME \
    # Cleanup
    && clean-layer.sh

### Install additional packages
RUN apt-get update && apt-get install -y --no-install-recommends \
    tuptime \
    nmap \
    iputils-tracepath \
    rename \
    whereami \
    tmate \
    tmux \
    zsh \
    ncdu \
    iftop \
    iotop \
    net-tools \
    tuptime \
    # Fix permissions
    && fix-permissions.sh $HOME \
    # Cleanup
    && clean-layer.sh \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /root
