version: "0.1"

info:
    name: "proneer/magento-dev-server"
    tags:
      - "v0.1"
      - "latest"
    maintainer: "Phillip Strefling"
    email: "phillip@proneer.co"
    organization: "Proneer Corp."
    version: "0.1"
    repository: "registry.dev.proneer.co"
    #build_dir: "../magento"
build:
    base: "ubuntu:20.04"
    projects:
      - directory: "base-cpu"
        dockerfiles:
          - file: "Dockerfile.base"
            repository: "registry.dev.proneer.co"
            name: "base-cpu"
            tag: "latest"
            push: "false"
            from: "ubuntu:20.04"
      - directory: "dev-server"
        dockerfiles:
          - file: "Dockerfile.dev"
            repository: "registry.dev.proneer.co"
            name: "base-dev"
            tag: "latest"
            push: "false"
            from: "registry.dev.proneer.co/base-cpu:latest"
      - directory: "lamp"
        dockerfiles:
          - file: "Dockerfile.base"
            repository: "registry.dev.proneer.co"
            name: "lamp"
            tag: "latest"
            push: "false"
            from: "registry.dev.proneer.co/base-dev:latest"
      - directory: "magento"
        dockerfiles:
          - file: "Dockerfile.base"
            repository: "registry.dev.proneer.co"
            name: "magento"
            tag: "latest"
            push: "false"
            from: "registry.dev.proneer.co/lamp:latest"
          - file: "Dockerfile.tools"
            repository: "registry.dev.proneer.co"
            name: "magento-tools"
            tag: "latest"
            push: "false"
            from: "registry.dev.proneer.co/magento:latest"
      - directory: "dev-server"
        dockerfiles:
          - file: "Dockerfile.vscode"
            repository: "registry.dev.proneer.co"
            name: "magento-dev-server"
            tag: "latest"
            push: "true"
            from: "registry.dev.proneer.co/magento-tools:latest"
            entrypoint: "python3 /docker-entrypoint.py"
